### ISSUE TITLE
Logotipo para a comunidade

### ISSUE THREAD

**Issue by akfzambrana** [front-ladies/frontladies.github.io#1]
Está aberta a chamada geral para criação do logotipo para a nossa comunidade.

## Orientações
- O logo possui dois blocos: "Front Ladies" + "sigla (de até 3 caracteres)"
- O logo precisará ser entregue em vetor para podermos utilizar ele em diversos tipos de midia. 
- Deverá utilizar somente fontes ou gráficos que sejam open-source e/ou de distribuição e uso gratuito.
- O resto é com a criatividade de vocês :smile: 

### Entrega
O prazo para entrega das sugestões é terça feira 01/03/2016 à meia noite (00:00)  

### Votação
A partir da quarta feira 02/03 ate o domingo dia 06/03 à meia noite (00:00)

## Processo de votação
O processo de votação será tratado em outra issue (que será criada após a finalização do prazo de entrega). 
Todas as pessoas poderão votar, no entanto o voto das mulheres (cis e trans) terá peso dois.

## Para envio da sua sugestão
É so responder esta issue, adicionando uma imagem com a sua sugestão e se desejar uma explicação a respeito do logo.

_Issue baseada na [issue do logo do FEMUG](https://github.com/femug/femug/issues/16). Obrigada pelo precedente @danielfilho_

**Comment by joselialcosta** [comment]
![logo-classe](https://cloud.githubusercontent.com/assets/9259883/13294027/d8e04aac-db00-11e5-9013-210d145c70d0.png)

**Comment by joselialcosta** [comment]
![logo](https://cloud.githubusercontent.com/assets/9259883/13295067/c3ddaf32-db05-11e5-95fb-b41484da8521.png)

**Comment by mayraasanto** [comment]
**Meninas, esses são os que fizemos ( Meu primo <Amaury> e Eu) espero que gostem!!! 
bjs - <Montagem das imagens feita por Amaury Sobrinho e participação Mayra Santos>. **

![frontend-mayra_2-1](https://cloud.githubusercontent.com/assets/17279715/13319576/6f1e42b2-dba1-11e5-8906-7ef9cb660936.jpg)

![img-20160224-wa0009](https://cloud.githubusercontent.com/assets/17279715/13319582/78886238-dba1-11e5-948e-8dbe7bbed371.jpg)

**Comment by ubirajarapelli** [comment]
01 - 
![front-ladies-abc-01](https://cloud.githubusercontent.com/assets/9123737/13327664/abc1bdca-dbc9-11e5-87fd-dd50c3643be0.jpg)
02 -
![front-ladies-abc-03](https://cloud.githubusercontent.com/assets/9123737/13327699/c214b758-dbc9-11e5-8985-511ef7ff4aae.jpg)

**Comment by ubirajarapelli** [comment]
01 - 
![front-ladies-abc-02](https://cloud.githubusercontent.com/assets/9123737/13327709/cec76c20-dbc9-11e5-9e8c-c6e2d4a3a130.jpg)

02 - 
![front-ladies-abc-04](https://cloud.githubusercontent.com/assets/9123737/13327725/d97b0b2c-dbc9-11e5-95da-88cdf435b371.jpg)

**Comment by mayraasanto** [comment]
Olá aqui estão minhas sugestões. 
Meu primo trabalhou as imagens na ideia que passei. 

Espero que gostem, se quiserem também dá pra aplicar outras ideias.

![img-20160229-wa0000](https://cloud.githubusercontent.com/assets/17279715/13414057/5669a23a-df2e-11e5-8d29-6f16f63b317a.jpg)

**Comment by tamihh** [comment]
Podemos estudar outras opções de cores também

![front_ladies_abc](https://cloud.githubusercontent.com/assets/6747662/13475707/22d49076-e0a3-11e5-9052-8fc5328443df.png)


![id_frontladies_v02](https://cloud.githubusercontent.com/assets/6747662/13475763/5e92a8f0-e0a3-11e5-9576-6be9b1756014.jpg)


![id_frontladies_v01](https://cloud.githubusercontent.com/assets/6747662/13475764/5e94ea48-e0a3-11e5-8f98-0a351fc8fc0d.jpg)

![id_frontladies_v03 1](https://cloud.githubusercontent.com/assets/6747662/13475824/9448a008-e0a3-11e5-9bc5-8819ed11b4db.jpg)

**Comment by akfzambrana** [comment]
Estou encerrando a issue para abrir o processo de votação :smile: 
Obrigada a todos os que participaram. Agora vamos escolher uhuu! :smile:
