### ISSUE TITLE
Votação para o logotipo

### ISSUE THREAD

**Issue by akfzambrana** [front-ladies/frontladies.github.io#2]
E ae pessoal, vamos votar no logo?

# Regras:
- Toda e qualquer pessoa que possuir conta no Github poderá votar
- Cada pessoa deverá escolher apenas uma opção de logotipo
- Os votos das mulheres tem peso dois (2), isto se deve a que a quantidade de mulheres é menor e o logo da comunidade será para representá-las
- Não é permitido fazer críticas ou comentários preconceituosos ou não construtivos sobre os logotipos.

# Como votar:
Para votar comente nesta issue somente com o número correspondente à sua escolha. 

### Opção xxx

# Prazo final para votação:
Domingo 06 de março de 2016 à meia noite.
<hr>

# Opção 001
![c3ddaf32-db05-11e5-95fb-b41484da8521](https://cloud.githubusercontent.com/assets/400922/13513814/6f5bd8f2-e182-11e5-8b74-a38d9a57d97e.png)

# Opção 002
![c214b758-dbc9-11e5-8985-511ef7ff4aae](https://cloud.githubusercontent.com/assets/400922/13513826/78104e88-e182-11e5-8f42-09f65fe6e55f.jpg)

# Opção 003
![abc1bdca-dbc9-11e5-87fd-dd50c3643be0](https://cloud.githubusercontent.com/assets/400922/13513836/93bf3464-e182-11e5-8b0e-da0fde1c02db.jpg)

# Opção 004
![cec76c20-dbc9-11e5-9e8c-c6e2d4a3a130](https://cloud.githubusercontent.com/assets/400922/13513842/a3fb7cde-e182-11e5-969a-325aae029b1a.jpg)

# Opção 005
![d97b0b2c-dbc9-11e5-95da-88cdf435b371](https://cloud.githubusercontent.com/assets/400922/13513848/af503296-e182-11e5-886a-4b0d4b722b32.jpg)

# Opção 006
![009](https://cloud.githubusercontent.com/assets/400922/13513991/9ebe6c76-e183-11e5-9406-e10f3d4699a8.png)

# Opção 007
![0010](https://cloud.githubusercontent.com/assets/400922/13513998/a4deb052-e183-11e5-824f-39eb081131f6.png)

# Opção 008
![001](https://cloud.githubusercontent.com/assets/400922/13514016/c0ea3514-e183-11e5-8291-aeb6f44520cc.png)

# Opção 009
![002](https://cloud.githubusercontent.com/assets/400922/13514018/c42bc026-e183-11e5-9ea7-701ab7287449.png)

# Opção 010
![003](https://cloud.githubusercontent.com/assets/400922/13514019/c7a27bbe-e183-11e5-90c8-255ee6d9e0b2.png)

# Opção 011
![004](https://cloud.githubusercontent.com/assets/400922/13514021/ccdd3146-e183-11e5-8cae-c9a9b962daa2.png)

# Opção 012
![005](https://cloud.githubusercontent.com/assets/400922/13514023/cff2b8ce-e183-11e5-9e95-853658f112c7.png)

# Opção 013
![006](https://cloud.githubusercontent.com/assets/400922/13514028/db30e4fe-e183-11e5-9b33-735d5ba72c03.png)

# Opção 014
![007](https://cloud.githubusercontent.com/assets/400922/13514036/e9612156-e183-11e5-8023-c52d61373b35.png)

# Opção 015
![008](https://cloud.githubusercontent.com/assets/400922/13514038/eca4e71c-e183-11e5-88c7-b7dffe42588b.png)

# Opção 016
![5e92a8f0-e0a3-11e5-9576-6be9b1756014](https://cloud.githubusercontent.com/assets/400922/13514041/f67ac432-e183-11e5-9063-38dc75c788e3.jpg)

# Opção 017
![5e94ea48-e0a3-11e5-8f98-0a351fc8fc0d](https://cloud.githubusercontent.com/assets/400922/13514048/04f090d2-e184-11e5-9c12-0969b5f70c24.jpg)

# Opção 018
![9448a008-e0a3-11e5-9bc5-8819ed11b4db](https://cloud.githubusercontent.com/assets/400922/13514052/090a3038-e184-11e5-84cb-b1d8788fc4cd.jpg)

**Comment by LarissaAbreu** [comment]
Opção 005

**Comment by LoraineRodrigues** [comment]
Opção 006.
Apesar de ter gostado mto tbm do 002. Rs

**Comment by eapmartins** [comment]
Opção 12

**Comment by tatishinoda** [comment]
Opção 002.

**Comment by WendellAdriel** [comment]
Opção 002.

**Comment by camilatigre** [comment]
Opção 002.

**Comment by marquinhusgoncalves** [comment]
Opção 002

**Comment by willianribeiro** [comment]
Opção 002

**Comment by acauamontiel** [comment]
Opção 005

**Comment by PedrinhoTc** [comment]
Option 2

**Comment by ilss13** [comment]
Opção 002

**Comment by Cleysonlb** [comment]
Opção 003

**Comment by victorkurauchi** [comment]
Opção 002

**Comment by felipeuliana** [comment]
Opção 010

**Comment by julialolato** [comment]
008

**Comment by marioleme** [comment]
Opção 005

**Comment by PKpacheco** [comment]
opção 005 ( mesmo tendo gostado de tantas outras :/ )

**Comment by dhelbegor** [comment]
Opção (2).

**Comment by tamihh** [comment]
opção 015

**Comment by robertacruzz** [comment]
Opção 14

**Comment by akfzambrana** [comment]
Opção 002

**Comment by akfzambrana** [comment]
Encerrado periodo para votação do nosso logo.

**Comment by akfzambrana** [comment]
Resultado da votação:
**Opção 02** = 3 (mulheres) e 7 (homens) **totalizando 13 votos**
**Opção 03** = 1 (homens) **totalizando 1 voto**
**Opção 05** = 2 (mulheres) e 2 (homens) **totalizando 6 votos**
**Opção 06** = 1 (mulheres) **totalizando 2 votos**
**Opção 08** = 1 (mulheres) **totalizando 2 votos**
**Opção 10** = 1 (homens) **totalizando 1 voto**
**Opção 12** = 1 (homens) **totalizando 1 voto**
**Opção 14** = 1 (mulheres) **totalizando 2 votos**
**Opção 15** = 1 (mulheres) **totalizando 1 votos**

Por tanto, o logotipo ganhador da votação é a opção 002 criada pelo @ubirajarapelli
Agradecemos a participação dos criadores e dos votantes :heart_eyes:
